import Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  HOST: Joi.string().default('0.0.0.0'),
  PORT: Joi.number().port().default(8787),
  PUBLIC_BASE_URL: Joi.string().uri().default('http://127.0.0.1:8787'),
  ALLOWED_ORIGINS: Joi.string().allow('').default(''),
  TRUST_PROXY: Joi.boolean().truthy('true').falsy('false').default(false),
  SWAGGER_ENABLED: Joi.boolean().truthy('true').falsy('false').default(true),
  LOG_LEVEL: Joi.string().default('info'),
  DATABASE_URL: Joi.string().required(),
  REDIS_URL: Joi.string().default('redis://127.0.0.1:6379/0'),
  REDIS_REQUIRED: Joi.boolean().truthy('true').falsy('false').default(false),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_REFRESH_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('30d'),
  SEED_ADMIN_USERNAME: Joi.string().default('hailin-admin'),
  SEED_ADMIN_PASSWORD: Joi.string().min(12).default('ChangeMe-Only-For-Local-2026'),
  SEED_ADMIN_DISPLAY_NAME: Joi.string().default('海林村超级管理员'),
  WECHAT_APP_ID: Joi.string().allow('').default(''),
  WECHAT_APP_SECRET: Joi.string().allow('').default(''),
  WECHAT_API_BASE_URL: Joi.string().uri().default('https://api.weixin.qq.com'),
  WECHAT_MOCK_ENABLED: Joi.boolean().truthy('true').falsy('false').default(true),
  WECHAT_PAY_APP_ID: Joi.string().allow('').default(''),
  WECHAT_PAY_MCH_ID: Joi.string().allow('').default(''),
  WECHAT_PAY_API_V3_KEY: Joi.string().allow('').default(''),
  WECHAT_PAY_SERIAL_NO: Joi.string().allow('').default(''),
  WECHAT_PAY_PRIVATE_KEY_PATH: Joi.string().allow('').default(''),
  WECHAT_PAY_PLATFORM_CERT_PATH: Joi.string().allow('').default(''),
  WECHAT_PAY_NOTIFY_URL: Joi.string().allow('').default(''),
  WECHAT_PAY_API_BASE_URL: Joi.string().uri().default('https://api.mch.weixin.qq.com'),
  AMAP_KEY: Joi.string().allow('').default(''),
  AMAP_API_BASE_URL: Joi.string().uri().default('https://restapi.amap.com'),
  EZVIZ_APP_KEY: Joi.string().allow('').default(''),
  EZVIZ_APP_SECRET: Joi.string().allow('').default(''),
  EZVIZ_API_BASE_URL: Joi.string().uri().default('https://open.ys7.com/api/lapp'),
  EZVIZ_MOCK_ENABLED: Joi.boolean().truthy('true').falsy('false').default(true),
  STORAGE_DRIVER: Joi.string().valid('local', 'cos').default('local'),
  LOCAL_UPLOAD_DIR: Joi.string().default('uploads'),
  UPLOAD_PUBLIC_PREFIX: Joi.string().default('/uploads'),
  UPLOAD_MAX_FILE_SIZE: Joi.number().integer().min(1).default(5242880),
  UPLOAD_MAX_FILES: Joi.number().integer().min(1).max(20).default(9),
  TENCENT_COS_SECRET_ID: Joi.string().allow('').default(''),
  TENCENT_COS_SECRET_KEY: Joi.string().allow('').default(''),
  TENCENT_COS_BUCKET: Joi.string().allow('').default(''),
  TENCENT_COS_REGION: Joi.string().allow('').default(''),
  TENCENT_COS_PUBLIC_BASE_URL: Joi.string().allow('').default(''),
  LLM_PROVIDER: Joi.string().default('kimi'),
  LLM_API_KEY: Joi.string().allow('').default(''),
  LLM_BASE_URL: Joi.string().uri().default('https://api.moonshot.cn/v1'),
  LLM_MODEL: Joi.string().default('kimi-k2.5'),
  LLM_TIMEOUT_MS: Joi.number().integer().min(1000).default(12000),
  MAX_PAGE_SIZE: Joi.number().integer().min(1).max(200).default(100),
  MAP_MAX_RADIUS_METERS: Joi.number().integer().min(100).default(20000),
  ORDER_PAYMENT_TIMEOUT_MINUTES: Joi.number().integer().min(1).default(30),
  RESERVATION_PAYMENT_TIMEOUT_MINUTES: Joi.number().integer().min(1).default(30),
  RATE_LIMIT_TTL_MS: Joi.number().integer().min(1000).default(60000),
  RATE_LIMIT_LIMIT: Joi.number().integer().min(1).default(120),
  LOGIN_RATE_LIMIT_LIMIT: Joi.number().integer().min(1).default(10),
  PLAY_URL_RATE_LIMIT_LIMIT: Joi.number().integer().min(1).default(20),
});
